devices([
  "iPhone 6s",
  "iPhone 5s"
])

languages([
  "en-US"
])

scheme "fastlanetestUITests"

output_directory "./fastlane/screenshots"

clear_previous_screenshots true

project "./fastlanetest.xcodeproj"
